FROM ubuntu
ENV TZ=America/Toronto
LABEL authors="stanley@secureailabs.com"
USER root
# Set tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3.9 \
    python3-venv \
    pip

# GIT
ARG git_personal_token
ARG branch
RUN git config --global url."https://$git_personal_token:@github.com/".insteadOf " https://github.com/"
RUN git clone -b  $branch https://$git_personal_token@github.com/secureailabs/Engineering.git /Test

# Set Working Directory
WORKDIR /Test/ApiServices
RUN git rev-parse --short HEAD

# Install dependencies for Test platform
RUN pip install -U pip setuptools wheel
RUN pip install -r config/requirements/all_requirements.txt --only-binary=:all: --no-binary=python-multipart,assertpy,cerberus

CMD ["/bin/bash"]
