FROM ubuntu
ENV TZ=America/Toronto
LABEL authors="stanley@secureailabs.com"
USER root
# Set tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3.9 \
    python3-venv \
    pip

# GIT
ARG git_personal_token
RUN git config --global url."https://$git_personal_token:@github.com/".insteadOf " https://github.com/"
RUN git clone https://$git_personal_token@github.com/secureailabs/Engineering.git /Test
WORKDIR /Test/ApiServices
RUN git pull
# RUN ./build/test_setup.sh
# RUN source venv38-sail_test/bin/activate

CMD ["/bin/bash"]
