#!/bin/bash
export AZURE_SUBSCRIPTION_ID=""
export AZURE_TENANT_ID=""
export AZURE_CLIENT_ID=""
export AZURE_CLIENT_SECRET=""
export AZURE_OBJECT_ID=""
export SLACK_WEBHOOK_URL=""
export DOCKER_REGISTRY_URL="developmentdockerregistry.azurecr.io"
export DOCKER_REGISTRY_USERNAME="DevelopmentDockerRegistry"
export DOCKER_REGISTRY_PASSWORD=""
export API_SERVICES_TAG="v0.1.0_c918c9e"
export AUDIT_SERVICES_TAG="v0.1.0_c918c9e"
export AGGREGATOR_SCN_TAG="v0.1.0_c918c9e"
export PARTICIPANT_SCN_TAG="v0.1.0_c918c9e"
export WEB_FRONTEND_TAG="v0.1.0_c918c9e"
