# The Root directory containing all the code
ROOTDIR=$(shell realpath ../..)
ABSROOTDIR=$(shell realpath $(ROOTDIR))

all:
	@cp PrivacySentinel.py $(ABSROOTDIR)/Binary/
	@cp PrivacySentinelPolicy.json $(ABSROOTDIR)/Binary/
