# The Root directory containing all the code
ROOTDIR=../..
ABSROOTDIR=$(shell realpath $(ROOTDIR))

all:
	@cp PrivacySentinel.py $(ABSROOTDIR)/Binary/
	@cp PrivacySentinelPolicy.json $(ABSROOTDIR)/Binary/
