//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftAzureInitializer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftAzureInitializer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;properties&quot;: {
        ///   &quot;templateLink&quot;: {
        ///     &quot;uri&quot;: &quot;{{TemplateUrl}}&quot;
        ///   },
        ///    &quot;parameters&quot;: {
        ///        &quot;vmName&quot;: {
        ///            &quot;value&quot;: &quot;{{VmName}}&quot;
        ///        },
        ///        &quot;vmSize&quot;: {
        ///            &quot;value&quot;: &quot;{{VmSize}}&quot;
        ///        },
        ///        &quot;networkSecurityGroupId&quot;: {
        ///            &quot;value&quot;: &quot;{{NetworkSecurityGroupId}}&quot;
        ///        },
        ///        &quot;virtualNetworkId&quot;: {
        ///            &quot;value&quot;:&quot;{{VirtualNetworkId}}&quot;
        ///        },
        ///        &quot;addressPrefix&quot;: {
        ///            &quot;value&quot;: &quot;10.1.16.0/24&quot;
        ///        },
        ///        &quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfidentialVirtualMachineDeploymentJson {
            get {
                return ResourceManager.GetString("ConfidentialVirtualMachineDeploymentJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When manually configuring the virtual machine settings
        ///in preparation for provisioning and initialization within
        ///Microsoft Azure, it should be noted that ALL of the
        ///virtual machines will be part of the same identical
        ///virtual machine cluster (i.e. shared cluster identifier)
        ///and all of the virtual machines will be configured to
        ///use the same digital contract and the same dataset..
        /// </summary>
        internal static string Help_001 {
            get {
                return ResourceManager.GetString("Help_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MicrosoftLogo {
            get {
                object obj = ResourceManager.GetObject("MicrosoftLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;location&quot;: &quot;{{Location}}&quot;
        ///}.
        /// </summary>
        internal static string ResourceGroupJson {
            get {
                return ResourceManager.GetString("ResourceGroupJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SAIL_Icon {
            get {
                object obj = ResourceManager.GetObject("SAIL_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SAIL_Icon1 {
            get {
                object obj = ResourceManager.GetObject("SAIL_Icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;location&quot;: &quot;{{Location}}&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;hardwareProfile&quot;: {
        ///      &quot;vmSize&quot;: &quot;Standard_D1_v2&quot;
        ///    },
        ///    &quot;storageProfile&quot;: {
        ///      &quot;imageReference&quot;: {
        ///        &quot;publisher&quot;: &quot;canonical&quot;,
        ///        &quot;offer&quot;: &quot;0001-com-ubuntu-server-focal&quot;,
        ///        &quot;sku&quot;: &quot;20_04-lts&quot;,
        ///        &quot;version&quot;: &quot;latest&quot;
        ///    },
        ///      &quot;osDisk&quot;: {
        ///        &quot;caching&quot;: &quot;ReadWrite&quot;,
        ///        &quot;managedDisk&quot;: {
        ///          &quot;storageAccountType&quot;: &quot;Standard_LRS&quot;
        ///        },
        ///        &quot;name&quot;: &quot;{{OsDiskName}}&quot;,
        ///        &quot;create [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VirtualMachineConfigurationJson {
            get {
                return ResourceManager.GetString("VirtualMachineConfigurationJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;properties&quot;: {
        ///   &quot;templateLink&quot;: {
        ///     &quot;uri&quot;: &quot;{{TemplateUrl}}&quot;
        ///   },
        ///    &quot;parameters&quot;: {
        ///        &quot;vmName&quot;: {
        ///            &quot;value&quot;: &quot;{{VmName}}&quot;
        ///        },
        ///        &quot;vmSize&quot;: {
        ///            &quot;value&quot;: &quot;{{VmSize}}&quot;
        ///        },
        ///        &quot;addressPrefix&quot;: {
        ///            &quot;value&quot;: &quot;10.1.16.0/24&quot;
        ///        },
        ///        &quot;subnetPrefix&quot;: {
        ///            &quot;value&quot;: &quot;10.1.16.0/24&quot;
        ///        },
        ///        &quot;osDiskType&quot;: {
        ///            &quot;value&quot;: &quot;StandardSSD_LRS&quot;
        ///        },
        ///        &quot;osType&quot;: {
        ///            &quot;value&quot;: &quot;L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VirtualMachineDeploymentJson {
            get {
                return ResourceManager.GetString("VirtualMachineDeploymentJson", resourceCulture);
            }
        }
    }
}
