# The Root directory containing all the code
ROOTDIR=$(shell realpath ..)
OUTPUT_DIR=$(ROOTDIR)/Binary/

.PHONY: all, clean

all:
	@mkdir -p $(OUTPUT_DIR)
	@cp vm_initializer.py $(OUTPUT_DIR)
	@cp sample_client.py $(OUTPUT_DIR)
	@cp decrypt_file.py $(OUTPUT_DIR)
