server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://auditserver:3100/loki/api/v1/push

scrape_configs:
- job_name: computation
  static_configs:
  - targets:
      - localhost
    labels:
      job: computation
      __path__: /app/rpc_audit.log
