name: Deploy Payload Images

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Owner of Deployment"
        required: true
        type: string

jobs:
  Setup_Environment:
    runs-on: [self-hosted, Linux, x64, docker]
    steps:
      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_BUILD_TOKEN }}
          persist-credentials: true
          submodules: true

      - name: Condition 2 Release Candidate
        run: |
          cd datascience
          ls
          git status
