name: Update Documentation

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Output HeadRef
        run: echo "${{ github.head_ref }}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start self-hosted runner
        run: |
          az vm start --subscription Build -g Dev-CI -n github-runner1

  clean:
    runs-on: [self-hosted, Linux, x64, docker]
    needs: start-runner
    steps:
      - name: cleanup
        run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          sudo chown -R $USER:$USER ${{ github.workspace }}

  build:
    runs-on: [self-hosted, Linux, x64, docker]
    needs: clean
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script, Build Binaries
        env:
          PAT: ${{ secrets.JENKINS_BUILD_TOKEN }}
        run: |
          set -e
          pwd
          ls -l
          sudo chmod 666 /var/run/docker.sock
          docker stop ubuntu_tst_bash || true && docker rm ubuntu_tst_bash || true
          docker stop apiservices || true && docker rm apiservices || true
          docker stop ubuntu_dev_CI || true && docker rm ubuntu_dev_CI || true
          rm -rf ./datascience/ || true
          git clone https://$PAT@github.com/secureailabs/datascience.git datascience
          git -C ./datascience/ submodule update --init --remote
          cd Docker/
          ./BuildImages.sh -i apiservices
          sudo ./RunService.sh -s apiservices -d
          sleep 60
          cd ..

  docs:
    runs-on: [self-hosted, Linux, x64, docker]
    needs: build
    steps:
      - name: Update Documentation
        run: |
          node -v
          redoc-cli --version
          rm -f ApiServices/docs/openapi.json
          wget https://127.0.0.1:8000/openapi.json -P ApiServices/docs/ --no-check-certificate
          redoc-cli bundle -o docs/index.html ApiServices/docs/openapi.json
          cp ApiServices/docs/ . -rf

      - name: check for changes
        run: git status

      - name: commit changed files
        run: |
          git config --local user.email "Jenkins@secureailabs.com"
          git config --local user.name "GitHub Action test"
          git add .
          git commit -m "Auto updating Docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: Documentation
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

  teardown:
    runs-on: [self-hosted, Linux, x64, docker]
    needs: docs
    steps:
      - name: Stop and Remove Docker Containers
        run: |
          set -e
          docker ps -a
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
          sudo make clean

  stop-runner:
    # Always stop runner even if build step fails
    if: always()
    runs-on: ubuntu-latest
    needs: [start-runner, build, teardown]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deallocate self-hosted runner
        run: |
          pwd
          ls -l
          az vm deallocate  --subscription Build -g Dev-CI -n github-runner1 --no-wait

  workflow-conclusion:
    # Without this step workflow remains "green" if build does fail.
    if: always()
    runs-on: ubuntu-latest
    needs: [start-runner, build, stop-runner]
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Job Status status and fail if they are red
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
