# Engineering
# wf_dispatch_deploy_platform.yml
# Deployment of Platform Services [api + Frontend] to a specified Subscription in Azure
#
# Copyright (C) 2022 Secure Ai Labs, Inc. All Rights Reserved.
# Private and Confidential. Internal Use Only.
#
#     This software contains proprietary information which shall not
#     be reproduced or transferred to other documents and shall not
#     be disclosed to others for any purpose without
#     prior written permission of Secure Ai Labs, Inc.
#
#

name: "Deploy Platform to Azure"

permissions:
  checks: read

on:
  workflow_call:
    inputs:
      subscription:
        description: "Choose Subscription"
        required: true
        type: string
        default: "Development"
      purpose:
        description: "Purpose of Deployment"
        required: true
        type: string
        default: "CI_TEST"
      owner:
        description: "Owner of Deployment"
        required: true
        type: string
        default: "CI_RUNNER"
      api_services_tag:
        description: "API Services Docker image Tag"
        required: true
        type: string
        default: "default"
      audit_service_tag:
        description: "Audit Service Docker image Tag"
        required: true
        type: string
        default: "default"
      aggregator_scn_tag:
        description: "Aggregator SCN Docker image Tag"
        required: true
        type: string
        default: "default"
      participant_scn_tag:
        description: "Participant SCN Docker image Tag"
        required: true
        type: string
        default: "default"
      preload_dataset:
        description: "Preload dataset with DatasetTool"
        required: true
        type: boolean
        default: false
      run_tests:
        description: Runs tests
        required: true
        type: boolean
        default: false
      deprovision_after:
        description: Deprovision after deployment
        required: true
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      subscription:
        description: "Choose Subscription"
        required: true
        type: choice
        default: "Development"
        options:
          - "Development"
          - "Release Candidate"
          - "ProductionGA"
      purpose:
        description: "Purpose of Deployment"
        required: true
        type: string
        default: "CI_TEST"
      api_services_tag:
        description: "API Services Docker image Tag"
        required: true
        type: string
        default: "default"
      audit_service_tag:
        description: "Audit Service Docker image Tag"
        required: true
        type: string
        default: "default"
      aggregator_scn_tag:
        description: "Aggregator SCN Docker image Tag"
        required: true
        type: string
        default: "default"
      participant_scn_tag:
        description: "Participant SCN Docker image Tag"
        required: true
        type: string
        default: "default"
      owner:
        description: "Owner of Deployment"
        required: true
        type: string
        default: "CI_RUNNER"
      preload_dataset:
        description: "Preload dataset with DatasetTool"
        required: true
        type: boolean
        default: false
      run_tests:
        description: Runs tests [Requires preloaded dataset]
        required: true
        type: boolean
        default: false
      deprovision_after:
        description: Deprovision after deployment
        required: true
        type: boolean
        default: false

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_DEPLOYPLATFORM_AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_DEPLOYPLATFORM_AZURE_CLIENT_SECRET }}
  AZURE_OBJECT_ID: ${{ secrets.AZURE_OBJECT_ID }}
  PUBLIC_IP: "False"

jobs:
  Deploy_Platform:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    container:
      image: developmentdockerregistry.azurecr.io/ciubuntu:v0.1.0_5f85ced
      credentials:
        username: ${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_PASSWORD }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Options selected
        run: |
          echo "## Options Selected" >> $GITHUB_STEP_SUMMARY
          echo "Subscription: ${{ inputs.subscription }}" >> $GITHUB_STEP_SUMMARY
          echo "Preload Datasets: ${{ inputs.preload_dataset }}" >> $GITHUB_STEP_SUMMARY
          echo "Purpose of Deployment: ${{ inputs.purpose }}" >> $GITHUB_STEP_SUMMARY
          echo "Owner of Deployment: ${{ inputs.owner }}" >> $GITHUB_STEP_SUMMARY
          echo "Container used [api_services_tag]: ${{ inputs.api_services_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Container used [audit_service_tag]: ${{ inputs.audit_service_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Container used [aggregator_scn_tag]: ${{ inputs.aggregator_scn_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Container used [participant_scn_tag]: ${{ inputs.participant_scn_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Run Tests after Deployment: ${{ inputs.run_tests }}" >> $GITHUB_STEP_SUMMARY
          echo "Deprovision when finished: ${{ inputs.deprovision_after }}" >> $GITHUB_STEP_SUMMARY

      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_BUILD_TOKEN }}
          persist-credentials: true
          submodules: true

      - name: Determine Subscription
        run: |
          echo "## Determine Subscription" >> $GITHUB_STEP_SUMMARY
          if ${{ inputs.subscription == 'Development' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_URL=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_URL }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_USERNAME=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_PASSWORD=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
            echo "Verified Subscription: Development" >> $GITHUB_STEP_SUMMARY
          elif ${{ inputs.subscription == 'Release Candidate' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.RELEASE_CANDIDATE_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_URL=${{ secrets.RELEASE_CANDIDATE_DOCKER_REGISTRY_URL }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_USERNAME=${{ secrets.RELEASE_CANDIDATE_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_PASSWORD=${{ secrets.RELEASE_CANDIDATE_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
            echo "Verified Subscription: Release Candidate" >> $GITHUB_STEP_SUMMARY
          elif ${{ inputs.subscription == 'ProductionGA' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.PRODUCTION_GA_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_URL=${{ secrets.PRODUCTION_GA_DOCKER_REGISTRY_URL }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_USERNAME=${{ secrets.PRODUCTION_GA_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_PASSWORD=${{ secrets.PRODUCTION_GA_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
            echo "Verified Subscription: Production GA" >> $GITHUB_STEP_SUMMARY
          else
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_URL=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_URL }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_USERNAME=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_REGISTRY_PASSWORD=${{ secrets.DEVELOPMENT_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
            echo "Verified Subscription: None (Defaulted to Development)" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Deploy To Subscription
        id: deploy_step
        run: |
          echo "## Deployment To Subscription" >> $GITHUB_STEP_SUMMARY
          set -e
          set -x
          ls -l
          exec 5>&1
          sed -i 's/$AZURE_SUBSCRIPTION_ID/'"$AZURE_SUBSCRIPTION_ID"'/g' deploy_config.sh
          sed -i 's/$AZURE_TENANT_ID/'"$AZURE_TENANT_ID"'/g' deploy_config.sh
          sed -i 's/$AZURE_CLIENT_ID/'"$AZURE_CLIENT_ID"'/g' deploy_config.sh
          sed -i 's/$AZURE_CLIENT_SECRET/'"$AZURE_CLIENT_SECRET"'/g' deploy_config.sh
          sed -i 's/$AZURE_OBJECT_ID/'"$AZURE_OBJECT_ID"'/g' deploy_config.sh
          sed -i 's/$SLACK_WEBHOOK_URL/'"$SLACK_WEBHOOK_URL"'/g' deploy_config.sh
          sed -i 's/$DOCKER_REGISTRY_URL/'"$DOCKER_REGISTRY_URL"'/g' deploy_config.sh
          sed -i 's/$DOCKER_REGISTRY_USERNAME/'"$DOCKER_REGISTRY_USERNAME"'/g' deploy_config.sh
          # Kindly ensure that the password does not contain @
          sed -i 's@$DOCKER_REGISTRY_PASSWORD@'"$DOCKER_REGISTRY_PASSWORD"'@g' deploy_config.sh
          if ${{ inputs.api_services_tag != 'default'}}
          then
            sed -i 's/$API_SERVICES_TAG/'"${{ inputs.api_services_tag }}"'/g' deploy_config.sh
          fi
          if ${{ inputs.audit_service_tag != 'default'}}
          then
            sed -i 's/$AUDIT_SERVICES_TAG/'"${{ inputs.audit_service_tag }}"'/g' deploy_config.sh
          fi
          if ${{ inputs.aggregator_scn_tag != 'default'}}
          then
            sed -i 's/$AGGREGATOR_SCN_TAG/'"${{ inputs.aggregator_scn_tag }}"'/g' deploy_config.sh
          fi
          if ${{ inputs.participant_scn_tag != 'default'}}
          then
            sed -i 's/$PARTICIPANT_SCN_TAG/'"${{ inputs.participant_scn_tag }}"'/g' deploy_config.sh
          fi

          DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ inputs.purpose }} -o ${{ inputs.owner }} -c | tee >(cat - >&5))

          INTERNAL_ADDR_API_SERVICE=$(echo "$DEPLOY_OUTPUT" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/")
          DEPLOY_GUID_ID=$(echo "$DEPLOY_OUTPUT" | grep  "Deployment GUID:" | cut -f2  -d ":")  

          echo "Sail API Services is hosted internally on: https://$INTERNAL_ADDR_API_SERVICE" >> $GITHUB_STEP_SUMMARY
          echo "Deployment GUID: $DEPLOY_GUID_ID" >> $GITHUB_STEP_SUMMARY

          echo "INTERNAL_ADDR_API_SERVICE=$INTERNAL_ADDR_API_SERVICE" >> $GITHUB_ENV
          echo "DEPLOY_GUID_ID=$DEPLOY_GUID_ID" >> $GITHUB_ENV

      - name: Read exported variables
        run: |
          echo "Test 1 : Exported Deployment GUID value: ${{ env.DEPLOY_GUID_ID }}" 
          echo "Test 2 : Exported Deployment GUID value: $DEPLOY_GUID_ID" >> $GITHUB_STEP_SUMMARY
          echo "Test 1 : Exported Internally hosted Sail API Services value: ${{ env.INTERNAL_ADDR_API_SERVICE }}"
          echo "Test 2 : Exported Internally hosted Sail API Services value: $INTERNAL_ADDR_API_SERVICE" >> $GITHUB_STEP_SUMMARY

      - name: Preload Datasets
        if: ${{ inputs.preload_dataset == true }}
        run: |
          echo "## Preload Dataset" >> $GITHUB_STEP_SUMMARY
          cd DatasetTool/
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          /root/.dotnet/dotnet build
          /root/.dotnet/dotnet publish -c Release
          dataset_output01=$(bin/Release/net6.0/linux-x64/publish/DatasetTool --email lbart@igr.com --password SailPassword@123 --config SampleData/igr_config.json --ip $INTERNAL_ADDR_API_SERVICE)
          dataset_output02=$(bin/Release/net6.0/linux-x64/publish/DatasetTool --email nadams@mghl.com --password SailPassword@123 --config SampleData/mghl_config.json --ip $INTERNAL_ADDR_API_SERVICE)
          echo "### Dataset 1" >> $GITHUB_STEP_SUMMARY
          echo "$dataset_output01" >> $GITHUB_STEP_SUMMARY
          echo "### Dataset 2" >> $GITHUB_STEP_SUMMARY
          echo "$dataset_output02" >> $GITHUB_STEP_SUMMARY

      - name: Run Tests
        if: ${{ inputs.run_tests == true }} && ${{ inputs.preload_dataset == true }}
        env:
          PAT: ${{ secrets.JENKINS_BUILD_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          deploy_output_str=$INTERNAL_ADDR_API_SERVICE
          INTERNAL_IP_ADDR=${deploy_output_str%:*}
          docker kill ubuntu_tst_bash || true && docker rm ubuntu_tst_bash || true
          docker build -t ubuntu-sailtap:1.0 --build-arg git_personal_token=$PAT --build-arg branch=$BRANCH_NAME -f CI_CD/Jenkins/Nightly_Tests/Dockerfile.test .
          docker run --name ubuntu_tst_bash -dit ubuntu-sailtap:1.0 /bin/bash
          echo "## Test Results" >>  $GITHUB_STEP_SUMMARY
          user_test_output=$(docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/sail_portal_api_test.py -m fastapi -sv --ip $INTERNAL_IP_ADDR  --port 8000")
          org_test_output=$(docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/sail_organization_api_test.py -m fastapi -sv --ip $INTERNAL_IP_ADDR  --port 8000")
          if ${{ inputs.preload_dataset == true }}; then
            dataset_test_output=$(docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/dataset_mgmt_api_test.py -m azure -sv --ip $INTERNAL_IP_ADDR  --port 8000")
          fi
          echo  "$user_test_output"
          echo "$org_test_output"
          echo "$dataset_test_output"

          test_output_str=""
          all_test_output=( $user_test_output $org_test_output $dataset_test_output )
          for line in "${all_test_output[@]}" ; do
            if [ "${line::15}" == "workflow_tests/" ]; then
              test_name=$(echo "${line##*::}")
              test_output_str=$(echo "${test_name%[*}")
            elif [ "${line}" = "PASSED" ] || [ "${line}" = "FAILED" ]; then
              echo "${test_output_str} | ${line}" >> $GITHUB_STEP_SUMMARY
            fi
          done
          docker kill ubuntu_tst_bash || true && docker rm ubuntu_tst_bash || true

      - name: Deprovision Deployment
        if: ${{ inputs.deprovision_after == true }}
        run: |
          echo "## Deprovision Platform" >> $GITHUB_STEP_SUMMARY
          echo "Purpose of Deployment: ${{ inputs.purpose }}" >> $GITHUB_STEP_SUMMARY
          echo "Owner of Deployment: ${{ inputs.owner }}" >> $GITHUB_STEP_SUMMARY
          echo "This is GUID of DEPLOYMENT for this CI RUN: $DEPLOY_GUID_ID" >> $GITHUB_STEP_SUMMARY
          set -e
          if [ "$DEPLOY_GUID_ID" = "" ] || [ "$DEPLOY_GUID_ID" = " " ] || [ ! "$DEPLOY_GUID_ID" ]; then
            echo "Deploy Canceled/Failed: Deprovision canceled." >> $GITHUB_STEP_SUMMARY
          else
            sudo chmod +x Deprovision.sh
            sudo -E ./Deprovision.sh -o CI_RUNNER <<<$(printf "3\n1\n${DEPLOY_GUID_ID}\ny\n") | tee deprov_output.txt
            echo "deprov_output=$(grep Deleting deprov_output.txt)" >> $GITHUB_STEP_SUMMARY
            rm deprov_output.txt
          fi
