# Engineering
# wf_dispatch_deploy_platform.yml
# Deployment of Platform Services [api + Frontend] to a specified Subscription in Azure
#
# Copyright (C) 2022 Secure Ai Labs, Inc. All Rights Reserved.
# Private and Confidential. Internal Use Only.
#
#     This software contains proprietary information which shall not
#     be reproduced or transferred to other documents and shall not
#     be disclosed to others for any purpose without
#     prior written permission of Secure Ai Labs, Inc.
#
#

name: "Deploy Platform to Azure"

permissions:
  checks: read

on:
  workflow_call:
    inputs:
      subscription:
        description: "Choose Subscription"
        required: true
        type: string
        default: "Development"
      purpose:
        description: "Purpose of Deployment"
        required: true
        type: string
        default: "CI_TEST"
      owner:
        description: "Owner of Deployment"
        required: true
        type: string
        default: "CI_RUNNER"
      preload_dataset:
        description: "Preload dataset with DatasetTool"
        required: true
        type: boolean
        default: false
      run_tests:
        description: Runs tests
        required: true
        type: boolean
        default: false
      deprovision_after:
        description: Deprovision after deployment
        required: true
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      subscription:
        description: "Choose Subscription"
        required: true
        type: choice
        default: "Development"
        options:
          - "Development"
          - "Release Candidate"
          - "ProductionGA"
      purpose:
        description: "Purpose of Deployment"
        required: true
        type: string
        default: "CI_TEST"
      owner:
        description: "Owner of Deployment"
        required: true
        type: string
        default: "CI_RUNNER"
      preload_dataset:
        description: "Preload dataset with DatasetTool"
        required: true
        type: boolean
        default: false
      run_tests:
        description: Runs tests [Requires preloaded dataset]
        required: true
        type: boolean
        default: false
      deprovision_after:
        description: Deprovision after deployment
        required: true
        type: boolean
        default: false

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_DEPLOYPLATFORM_AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_DEPLOYPLATFORM_AZURE_CLIENT_SECRET }}
  AZURE_OBJECT_ID: ${{ secrets.AZURE_OBJECT_ID }}
  PUBLIC_IP: "False"

jobs:
  Setup_Environment:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    steps:
      - name: Options selected
        run: |
          echo "Subscription: ${{ inputs.subscription }}"
          echo "Preload Datasets: ${{ inputs.preload_dataset }}"
          echo "Purpose of Deployment: ${{ inputs.purpose }}"
          echo "Owner of Deployment: ${{ inputs.owner }}"
          echo "Run Tests after Deployment: ${{ inputs.run_tests }}"
          echo "Deprovision when finished: ${{ inputs.deprovision_after }}"

      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_BUILD_TOKEN }}
          persist-credentials: true
          submodules: true

  Deploy_Platform:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    needs: Setup_Environment
    outputs:
      internal_ip_addr: ${{ steps.deploy_step.outputs.INTERNAL_IP_ADDR }}
      deployment_id: ${{ steps.deploy_step.outputs.DEPLOY_ID }}
    steps:
      - name: Determine Subscription
        run: |
          if ${{ inputs.subscription == 'Development' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Development"
          elif ${{ inputs.subscription == 'Release Candidate' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.RELEASE_CANDIDATE_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Release Candidate"
          elif ${{ inputs.subscription == 'ProductionGA' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.PRODUCTION_GA_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Production GA"
          else
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: None (Defaulted to Development)"
          fi

      - name: Deploy To Subscription
        id: deploy_step
        run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          sudo chown -R $USER:$USER ${{ github.workspace }}
          set -e
          pwd
          ls -l
          exec 5>&1
          mkdir Binary || true
          DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ inputs.purpose }} -o ${{ inputs.owner }} |tee >(cat - >&5))
          INTERNAL_ADDR_API_SERVICE=$(echo "$DEPLOY_OUTPUT" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/" | tee >(cat - >&5))
          echo "INTERNAL_IP_ADDR=$INTERNAL_ADDR_API_SERVICE" >> $GITHUB_OUTPUT
          DEPLOY_GUID_ID=$(echo "$DEPLOY_OUTPUT" | grep  "Deployment GUID:" | cut -f2  -d ":" | tee >(cat - >&5))
          echo "DEPLOY_ID=$DEPLOY_GUID_ID" >> $GITHUB_OUTPUT
          if ${{ inputs.preload_dataset == true }}; then
            cd DatasetTool/
            dotnet build
            dotnet publish -c Release
            bin/Release/net6.0/linux-x64/publish/DatasetTool --email lbart@igr.com --password SailPassword@123 --config SampleData/igr_config.json --ip $INTERNAL_ADDR_API_SERVICE
            bin/Release/net6.0/linux-x64/publish/DatasetTool --email nadams@mghl.com --password SailPassword@123 --config SampleData/mghl_config.json --ip $INTERNAL_ADDR_API_SERVICE
          else
            echo "Not Preloading Datasets."
          fi

  Test:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    if: ${{ inputs.run_tests == true }}
    needs: Deploy_Platform
    steps:
      - name: Run Tests
        env:
          PAT: ${{ secrets.JENKINS_BUILD_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          if ${{ inputs.run_tests == true }}; then
            deploy_output_str=${{needs.Deploy_Platform.outputs.internal_ip_addr}}
            INTERNAL_IP_ADDR=${deploy_output_str%:*}
            docker stop ubuntu_tst_bash || true && docker rm ubuntu_tst_bash || true
            docker build -t ubuntu-sailtap:1.0 --build-arg git_personal_token=$PAT --build-arg branch=$BRANCH_NAME -f CI_CD/Jenkins/Nightly_Tests/Dockerfile.test .
            docker run --name ubuntu_tst_bash -dit ubuntu-sailtap:1.0 /bin/bash
            docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/sail_portal_api_test.py -m "fastapi" -sv --ip $INTERNAL_IP_ADDR  --port 8000"
            docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/sail_organization_api_test.py -m "fastapi" -sv --ip $INTERNAL_IP_ADDR  --port 8000"
            docker exec -w /Test/ApiServices/tests ubuntu_tst_bash sh -c "pytest workflow_tests/test_api/test_backend/dataset_mgmt_api_test.py -m "azure" -sv --ip $INTERNAL_IP_ADDR  --port 8000"
          fi
          docker kill ubuntu_tst_bash || true && docker rm ubuntu_tst_bash || true

  Check_Test_Selection:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    needs: [Deploy_Platform, Test]
    if: |
      always() &&
      (needs.Test.result == 'success' || needs.Test.result == 'skipped')
    outputs:
      check: ${{ steps.check.outputs.run_test }}
    steps:
      - name: Verified Test option selected
        id: check
        run: |
          if ${{ inputs.run_tests == true }}; then
            echo "run_test=yes" >> $GITHUB_OUTPUT
          else
            echo "run_test=no" >> $GITHUB_OUTPUT
          fi

  Deprovision_Platform:
    runs-on: [self-hosted, Linux, x64, docker, Platform]
    env:
      CHECKTESTRAN: ${{needs.Check_Test_Selection.outputs.check}}
    if: |
      always() &&
      (needs.Check_Test_Selection.result == 'success')
    needs: [Deploy_Platform, Check_Test_Selection]
    steps:
      - name: Deprovision Parameters
        run: |
          echo "CHECK TEST RAN: $CHECKTESTRAN"
          if ${{ inputs.deprovision_after == true }}; then
            echo "Purpose of Deployment: ${{ inputs.purpose }}"
            echo "Owner of Deployment: ${{ inputs.owner }}"
            deployment_id="${{needs.Deploy_Platform.outputs.deployment_id}}"
            echo "This is GUID of DEPLOYMENT for this CI RUN: $deployment_id"
          else
            echo "Step Display Deprovision Parameters not required"
            echo "deprovision_after option was not selected"
          fi

      - name: Determine Subscription
        run: |
          if ${{ inputs.subscription == 'Development' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Development"
          elif ${{ inputs.subscription == 'Release Candidate' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.RELEASE_CANDIDATE_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Release Candidate"
          elif ${{ inputs.subscription == 'ProductionGA' }}; then
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.PRODUCTION_GA_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: Production GA"
          else
            echo "AZURE_SUBSCRIPTION_ID=${{ secrets.DEVELOPMENT_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
            echo "Subscription: None (Defaulted to Development)"
          fi

      - name: Deprovision
        run: |
          if ${{ inputs.deprovision_after == true }}; then
            echo "Purpose of Deployment: ${{ inputs.purpose }}"
            echo "Owner of Deployment: ${{ inputs.owner }}"
            deployment_id="${{needs.Deploy_Platform.outputs.deployment_id}}"
            echo "This is GUID of DEPLOYMENT for this CI RUN: $deployment_id"
            set -e
            pwd
            if [ "$deployment_id" = "" ] || [ "$deployment_id" = " " ] || [ ! "$deployment_id" ]; then
              echo "Deploy Canceled/Failed: Deprovision canceled."
            else
              chmod +x Deprovision.sh
              sudo -E ./Deprovision.sh -o CI_RUNNER <<<$(printf "3\n1\n${deployment_id}\ny\n")
            fi
          else
            echo "Step Deprovision not required"
            echo "deprovision_after option was not selected"
          fi
